server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:~/kakaopaydb
    url: jdbc:h2:file:./src/main/resources/kakaopaydb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com:
      kakaopay: debug
    org:
      hibernate:
        type: trace
