

## 조회
GET localhost:8080/kakaopay/spread/DT7
Content-Type: application/json
X-USER-ID: 1004
X-ROOM-ID: room-1000-02

### 받기
PUT localhost:8080/kakaopay/spread/43L
Content-Type: application/json
X-USER-ID: 2344
X-ROOM-ID: room-486-02

### 뿌리기
POST localhost:8080/kakaopay/spread
Content-Type: application/json
X-USER-ID: 1004
X-ROOM-ID: room-1000-02

{
  "money": "20000",
  "count": "2"
}

###

