

##
GET localhost:8080/kakaopay/spread/ta2
Content-Type: application/json
X-USER-ID: 1004
X-ROOM-ID: room-1004-01

###
PUT localhost:8080/kakaopay/spread/ta2
Content-Type: application/json
X-USER-ID: 3882
X-ROOM-ID: room-1004-01

###
POST localhost:8080/kakaopay/spread
Content-Type: application/json
X-USER-ID: 1004
X-ROOM-ID: room-1004-01

{
  "money": "10000",
  "count": "5"
}

###
POST localhost:8080/kakaopay/spread
Content-Type: application/json
X-USER-ID: 486
X-ROOM-ID: room-486-02

{
  "money": "9999",
  "count": "100"
}

###

